# Generated by Django 4.2.9 on 2025-03-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BulkUploadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.UUIDField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                ("total_users", models.IntegerField(default=0)),
                ("processed_users", models.IntegerField(default=0)),
                ("created_users", models.JSONField(default=list)),
                ("errors", models.JSONField(default=list)),
                ("file_name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
