# Generated by Django 4.2.9 on 2025-03-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkuploadtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("DELETED", "Deleted"),
                ],
                default="PROCESSING",
                max_length=20,
            ),
        ),
    ]
