# Generated by Django 4.2.9 on 2025-03-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0003_remove_bulkuploadtask_task_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkUploadUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("password", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("EXISTING", "Already Exists"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameField(
            model_name="bulkuploadtask",
            old_name="processed_users",
            new_name="processed_rows",
        ),
        migrations.RenameField(
            model_name="bulkuploadtask",
            old_name="total_users",
            new_name="total_rows",
        ),
        migrations.RemoveField(
            model_name="bulkuploadtask",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="bulkuploadtask",
            name="created_users",
        ),
        migrations.RemoveField(
            model_name="bulkuploadtask",
            name="errors",
        ),
        migrations.AlterField(
            model_name="bulkuploadtask",
            name="file_name",
            field=models.CharField(default="default.csv", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bulkuploadtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="WAITING",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="BulkUploadTaskUser",
        ),
        migrations.AddField(
            model_name="bulkuploaduser",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="admin_panel.bulkuploadtask",
            ),
        ),
    ]
