# Generated by Django 4.2.9 on 2025-04-08 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserContentPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_preference", models.IntegerField(default=50)),
                ("audio_preference", models.IntegerField(default=50)),
                ("recency_preference", models.IntegerField(default=50)),
                ("diversity_preference", models.IntegerField(default=50)),
                ("tag_preferences", models.JSONField(default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserInterestGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest_graph", models.JSONField(default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="postview",
            name="view_duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="postinteraction",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="posts.post",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["post"], name="posts_comme_post_id_06cfd5_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author"], name="posts_comme_author__a503ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_at"], name="posts_comme_created_f825cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["created_at"], name="posts_post_created_dadbfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["author"], name="posts_post_author__19d68b_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["type"], name="posts_post_type_4505ab_idx"),
        ),
        migrations.AddIndex(
            model_name="postinteraction",
            index=models.Index(
                fields=["user", "interaction_type"],
                name="posts_posti_user_id_3f4a61_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postinteraction",
            index=models.Index(
                fields=["post", "interaction_type"],
                name="posts_posti_post_id_76cfc4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postinteraction",
            index=models.Index(
                fields=["created_at"], name="posts_posti_created_a0320a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postview",
            index=models.Index(fields=["post"], name="posts_postv_post_id_f41258_idx"),
        ),
        migrations.AddIndex(
            model_name="postview",
            index=models.Index(fields=["user"], name="posts_postv_user_id_897a8f_idx"),
        ),
        migrations.AddIndex(
            model_name="postview",
            index=models.Index(
                fields=["created_at"], name="posts_postv_created_b3416a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trendingscore",
            index=models.Index(fields=["-score"], name="posts_trend_score_3c368b_idx"),
        ),
        migrations.AddField(
            model_name="userinterestgraph",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interest_graph",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usercontentpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="posts.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="userinterestgraph",
            index=models.Index(fields=["user"], name="posts_useri_user_id_4c80f2_idx"),
        ),
        migrations.AddIndex(
            model_name="userinterestgraph",
            index=models.Index(
                fields=["last_updated"], name="posts_useri_last_up_0ae3f5_idx"
            ),
        ),
    ]
